
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22621 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      Microsoft (R) Visual Studio Version 9.0.30729.1.
      Copyright (C) Microsoft Corp. All rights reserved.
      1>------ Build started: Project: CompilerIdC, Configuration: Debug Win32 ------
      1>Compiling...
      1>CMakeCCompilerId.c
      1>Linking...
      1>Embedding manifest...
      1>Performing Post-Build Event...
      1>CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\bin\\cl.exe
      1>Build log was saved at "file://c:\\Users\\rekon\\source\\repos\\Prime-World-2022\\pw\\branches\\r1117\\Src\\UniServerApp\\CMakeFiles\\3.29.5\\CompilerIdC\\Debug\\BuildLog.htm"
      1>CompilerIdC - 0 error(s), 0 warning(s)
      ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/rekon/source/repos/Prime-World-2022/pw/branches/r1117/Src/UniServerApp/CMakeFiles/3.29.5/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      Microsoft (R) Visual Studio Version 9.0.30729.1.
      Copyright (C) Microsoft Corp. All rights reserved.
      1>------ Build started: Project: CompilerIdCXX, Configuration: Debug Win32 ------
      1>Compiling...
      1>CMakeCXXCompilerId.cpp
      1>Linking...
      1>Embedding manifest...
      1>Performing Post-Build Event...
      1>CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\bin\\cl.exe
      1>Build log was saved at "file://c:\\Users\\rekon\\source\\repos\\Prime-World-2022\\pw\\branches\\r1117\\Src\\UniServerApp\\CMakeFiles\\3.29.5\\CompilerIdCXX\\Debug\\BuildLog.htm"
      1>CompilerIdCXX - 0 error(s), 0 warning(s)
      ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/rekon/source/repos/Prime-World-2022/pw/branches/r1117/Src/UniServerApp/CMakeFiles/3.29.5/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/rekon/source/repos/Prime-World-2022/pw/branches/r1117/Src/UniServerApp/CMakeFiles/CMakeScratch/TryCompile-mkic4y"
      binary: "C:/Users/rekon/source/repos/Prime-World-2022/pw/branches/r1117/Src/UniServerApp/CMakeFiles/CMakeScratch/TryCompile-mkic4y"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/rekon/source/repos/Prime-World-2022/pw/branches/r1117/Src/UniServerApp/CMakeFiles/CMakeScratch/TryCompile-mkic4y'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/devenv.com" CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_827bd
        
        Microsoft (R) Visual Studio Version 9.0.30729.1.
        Copyright (C) Microsoft Corp. All rights reserved.
        1>------ Build started: Project: cmTC_827bd, Configuration: Debug Win32 ------
        1>Compiling...
        1>Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.30729.01 for 80x86
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>cl /Od /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\\"Debug\\"" /D "_MBCS" /FD /RTC1 /MDd /Fo"cmTC_827bd.dir\\Debug\\\\" /Fd"cmTC_827bd.dir\\Debug\\vc90.pdb" /W3 /c /Zi /TC "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCCompilerABI.c"
        1>CMakeCCompilerABI.c
        1>Compiling manifest to resources...
        1>Microsoft (R) Windows (R) Resource Compiler Version 6.1.6723.1
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>Linking...
        1>Embedding manifest...
        1>Microsoft (R) Windows (R) Resource Compiler Version 6.1.6723.1
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>Build log was saved at "file://c:\\Users\\rekon\\source\\repos\\Prime-World-2022\\pw\\branches\\r1117\\Src\\UniServerApp\\CMakeFiles\\CMakeScratch\\TryCompile-mkic4y\\cmTC_827bd.dir\\Debug\\BuildLog.htm"
        1>cmTC_827bd - 0 error(s), 0 warning(s)
        ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:173 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:67 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/rekon/source/repos/Prime-World-2022/pw/branches/r1117/Src/UniServerApp/CMakeFiles/CMakeScratch/TryCompile-4l5bsv"
      binary: "C:/Users/rekon/source/repos/Prime-World-2022/pw/branches/r1117/Src/UniServerApp/CMakeFiles/CMakeScratch/TryCompile-4l5bsv"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_SCAN_FOR_MODULES: "OFF"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/rekon/source/repos/Prime-World-2022/pw/branches/r1117/Src/UniServerApp/CMakeFiles/CMakeScratch/TryCompile-4l5bsv'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/devenv.com" CMAKE_TRY_COMPILE.sln /build Debug /project cmTC_aca74
        
        Microsoft (R) Visual Studio Version 9.0.30729.1.
        Copyright (C) Microsoft Corp. All rights reserved.
        1>------ Build started: Project: cmTC_aca74, Configuration: Debug Win32 ------
        1>Compiling...
        1>Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 15.00.30729.01 for 80x86
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>cl /Od /D "WIN32" /D "_WINDOWS" /D "CMAKE_INTDIR=\\"Debug\\"" /D "_MBCS" /FD /EHsc /RTC1 /MDd /Fo"cmTC_aca74.dir\\Debug\\\\" /Fd"cmTC_aca74.dir\\Debug\\vc90.pdb" /W3 /c /Zi /TP "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files\\CMake\\share\\cmake-3.29\\Modules\\CMakeCXXCompilerABI.cpp"
        1>CMakeCXXCompilerABI.cpp
        1>Compiling manifest to resources...
        1>Microsoft (R) Windows (R) Resource Compiler Version 6.1.6723.1
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>Linking...
        1>Embedding manifest...
        1>Microsoft (R) Windows (R) Resource Compiler Version 6.1.6723.1
        1>Copyright (C) Microsoft Corporation.  All rights reserved.
        1>Build log was saved at "file://c:\\Users\\rekon\\source\\repos\\Prime-World-2022\\pw\\branches\\r1117\\Src\\UniServerApp\\CMakeFiles\\CMakeScratch\\TryCompile-4l5bsv\\cmTC_aca74.dir\\Debug\\BuildLog.htm"
        1>cmTC_aca74 - 0 error(s), 0 warning(s)
        ========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineCompilerABI.cmake:173 (message)"
      - "C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Parsed CXX implicit link information:
        link line regex: [^( *|.*[/\\])(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        linker tool regex: [^[ 	]*(->|")?[ 	]*(([^"]*[/\\])?(ld[0-9]*(\\.[a-z]+)?|link\\.exe|lld-link(\\.exe)?))("|,| |$)]
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...
